<?xml version="1.0" encoding="utf-8"?><Database Name="bd_catalogo" Class="ConexionBDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=bd_catalogo;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bd_catalogoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Fabricante" Member="Fabricante">
    <Type Name="Fabricante">
      <Column Name="id_Fabricante" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Fabricante_Smartphone" Member="Smartphone" ThisKey="id_Fabricante" OtherKey="id_Fabricante" Type="Smartphone" />
    </Type>
  </Table>
  <Table Name="dbo.Smartphone" Member="Smartphone">
    <Type Name="Smartphone">
      <Column Name="id_Smartphone" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Imagen" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="id_Fabricante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pantalla" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Procesador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Camara" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Memoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Almacenamiento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SistemaOperativo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Bateria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SAP" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CodigoBarra" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Fabricante_Smartphone" Member="Fabricante" ThisKey="id_Fabricante" OtherKey="id_Fabricante" Type="Fabricante" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.vPhones" Method="vPhones">
    <ElementType Name="vPhonesResult">
      <Column Name="id_Smartphone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Imagen" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Fabricante" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>