#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_catalogo")]
public partial class ConexionBDDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertFabricante(Fabricante instance);
  partial void UpdateFabricante(Fabricante instance);
  partial void DeleteFabricante(Fabricante instance);
  partial void InsertSmartphone(Smartphone instance);
  partial void UpdateSmartphone(Smartphone instance);
  partial void DeleteSmartphone(Smartphone instance);
  partial void InsertEstado_Usuario(Estado_Usuario instance);
  partial void UpdateEstado_Usuario(Estado_Usuario instance);
  partial void DeleteEstado_Usuario(Estado_Usuario instance);
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  #endregion
	
	public ConexionBDDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bd_catalogoConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionBDDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionBDDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ConexionBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Fabricante> Fabricante
	{
		get
		{
			return this.GetTable<Fabricante>();
		}
	}
	
	public System.Data.Linq.Table<Smartphone> Smartphone
	{
		get
		{
			return this.GetTable<Smartphone>();
		}
	}
	
	public System.Data.Linq.Table<Estado_Usuario> Estado_Usuario
	{
		get
		{
			return this.GetTable<Estado_Usuario>();
		}
	}
	
	public System.Data.Linq.Table<Usuario> Usuario
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.vPhones")]
	public ISingleResult<vPhonesResult> vPhones()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<vPhonesResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fabricante")]
public partial class Fabricante : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Fabricante;
	
	private string _Descripcion;
	
	private EntitySet<Smartphone> _Smartphone;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_FabricanteChanging(int value);
    partial void Onid_FabricanteChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
	
	public Fabricante()
	{
		this._Smartphone = new EntitySet<Smartphone>(new Action<Smartphone>(this.attach_Smartphone), new Action<Smartphone>(this.detach_Smartphone));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Fabricante", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Fabricante
	{
		get
		{
			return this._id_Fabricante;
		}
		set
		{
			if ((this._id_Fabricante != value))
			{
				this.Onid_FabricanteChanging(value);
				this.SendPropertyChanging();
				this._id_Fabricante = value;
				this.SendPropertyChanged("id_Fabricante");
				this.Onid_FabricanteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Descripcion
	{
		get
		{
			return this._Descripcion;
		}
		set
		{
			if ((this._Descripcion != value))
			{
				this.OnDescripcionChanging(value);
				this.SendPropertyChanging();
				this._Descripcion = value;
				this.SendPropertyChanged("Descripcion");
				this.OnDescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fabricante_Smartphone", Storage="_Smartphone", ThisKey="id_Fabricante", OtherKey="id_Fabricante")]
	public EntitySet<Smartphone> Smartphone
	{
		get
		{
			return this._Smartphone;
		}
		set
		{
			this._Smartphone.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Smartphone(Smartphone entity)
	{
		this.SendPropertyChanging();
		entity.Fabricante = this;
	}
	
	private void detach_Smartphone(Smartphone entity)
	{
		this.SendPropertyChanging();
		entity.Fabricante = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Smartphone")]
public partial class Smartphone : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Smartphone;
	
	private string _Nombre;
	
	private string _Imagen;
	
	private int _id_Fabricante;
	
	private string _Pantalla;
	
	private string _Procesador;
	
	private string _Camara;
	
	private string _Memoria;
	
	private string _Almacenamiento;
	
	private string _SistemaOperativo;
	
	private string _Bateria;
	
	private string _SAP;
	
	private string _CodigoBarra;
	
	private EntityRef<Fabricante> _Fabricante;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_SmartphoneChanging(int value);
    partial void Onid_SmartphoneChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnImagenChanging(string value);
    partial void OnImagenChanged();
    partial void Onid_FabricanteChanging(int value);
    partial void Onid_FabricanteChanged();
    partial void OnPantallaChanging(string value);
    partial void OnPantallaChanged();
    partial void OnProcesadorChanging(string value);
    partial void OnProcesadorChanged();
    partial void OnCamaraChanging(string value);
    partial void OnCamaraChanged();
    partial void OnMemoriaChanging(string value);
    partial void OnMemoriaChanged();
    partial void OnAlmacenamientoChanging(string value);
    partial void OnAlmacenamientoChanged();
    partial void OnSistemaOperativoChanging(string value);
    partial void OnSistemaOperativoChanged();
    partial void OnBateriaChanging(string value);
    partial void OnBateriaChanged();
    partial void OnSAPChanging(string value);
    partial void OnSAPChanged();
    partial void OnCodigoBarraChanging(string value);
    partial void OnCodigoBarraChanged();
    #endregion
	
	public Smartphone()
	{
		this._Fabricante = default(EntityRef<Fabricante>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Smartphone", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Smartphone
	{
		get
		{
			return this._id_Smartphone;
		}
		set
		{
			if ((this._id_Smartphone != value))
			{
				this.Onid_SmartphoneChanging(value);
				this.SendPropertyChanging();
				this._id_Smartphone = value;
				this.SendPropertyChanged("id_Smartphone");
				this.Onid_SmartphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string Imagen
	{
		get
		{
			return this._Imagen;
		}
		set
		{
			if ((this._Imagen != value))
			{
				this.OnImagenChanging(value);
				this.SendPropertyChanging();
				this._Imagen = value;
				this.SendPropertyChanged("Imagen");
				this.OnImagenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Fabricante", DbType="Int NOT NULL")]
	public int id_Fabricante
	{
		get
		{
			return this._id_Fabricante;
		}
		set
		{
			if ((this._id_Fabricante != value))
			{
				if (this._Fabricante.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_FabricanteChanging(value);
				this.SendPropertyChanging();
				this._id_Fabricante = value;
				this.SendPropertyChanged("id_Fabricante");
				this.Onid_FabricanteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pantalla", DbType="VarChar(50)")]
	public string Pantalla
	{
		get
		{
			return this._Pantalla;
		}
		set
		{
			if ((this._Pantalla != value))
			{
				this.OnPantallaChanging(value);
				this.SendPropertyChanging();
				this._Pantalla = value;
				this.SendPropertyChanged("Pantalla");
				this.OnPantallaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Procesador", DbType="VarChar(50)")]
	public string Procesador
	{
		get
		{
			return this._Procesador;
		}
		set
		{
			if ((this._Procesador != value))
			{
				this.OnProcesadorChanging(value);
				this.SendPropertyChanging();
				this._Procesador = value;
				this.SendPropertyChanged("Procesador");
				this.OnProcesadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camara", DbType="VarChar(50)")]
	public string Camara
	{
		get
		{
			return this._Camara;
		}
		set
		{
			if ((this._Camara != value))
			{
				this.OnCamaraChanging(value);
				this.SendPropertyChanging();
				this._Camara = value;
				this.SendPropertyChanged("Camara");
				this.OnCamaraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memoria", DbType="VarChar(50)")]
	public string Memoria
	{
		get
		{
			return this._Memoria;
		}
		set
		{
			if ((this._Memoria != value))
			{
				this.OnMemoriaChanging(value);
				this.SendPropertyChanging();
				this._Memoria = value;
				this.SendPropertyChanged("Memoria");
				this.OnMemoriaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Almacenamiento", DbType="VarChar(50)")]
	public string Almacenamiento
	{
		get
		{
			return this._Almacenamiento;
		}
		set
		{
			if ((this._Almacenamiento != value))
			{
				this.OnAlmacenamientoChanging(value);
				this.SendPropertyChanging();
				this._Almacenamiento = value;
				this.SendPropertyChanged("Almacenamiento");
				this.OnAlmacenamientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SistemaOperativo", DbType="VarChar(50)")]
	public string SistemaOperativo
	{
		get
		{
			return this._SistemaOperativo;
		}
		set
		{
			if ((this._SistemaOperativo != value))
			{
				this.OnSistemaOperativoChanging(value);
				this.SendPropertyChanging();
				this._SistemaOperativo = value;
				this.SendPropertyChanged("SistemaOperativo");
				this.OnSistemaOperativoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bateria", DbType="VarChar(50)")]
	public string Bateria
	{
		get
		{
			return this._Bateria;
		}
		set
		{
			if ((this._Bateria != value))
			{
				this.OnBateriaChanging(value);
				this.SendPropertyChanging();
				this._Bateria = value;
				this.SendPropertyChanged("Bateria");
				this.OnBateriaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAP", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string SAP
	{
		get
		{
			return this._SAP;
		}
		set
		{
			if ((this._SAP != value))
			{
				this.OnSAPChanging(value);
				this.SendPropertyChanging();
				this._SAP = value;
				this.SendPropertyChanged("SAP");
				this.OnSAPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoBarra", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string CodigoBarra
	{
		get
		{
			return this._CodigoBarra;
		}
		set
		{
			if ((this._CodigoBarra != value))
			{
				this.OnCodigoBarraChanging(value);
				this.SendPropertyChanging();
				this._CodigoBarra = value;
				this.SendPropertyChanged("CodigoBarra");
				this.OnCodigoBarraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fabricante_Smartphone", Storage="_Fabricante", ThisKey="id_Fabricante", OtherKey="id_Fabricante", IsForeignKey=true)]
	public Fabricante Fabricante
	{
		get
		{
			return this._Fabricante.Entity;
		}
		set
		{
			Fabricante previousValue = this._Fabricante.Entity;
			if (((previousValue != value) 
						|| (this._Fabricante.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Fabricante.Entity = null;
					previousValue.Smartphone.Remove(this);
				}
				this._Fabricante.Entity = value;
				if ((value != null))
				{
					value.Smartphone.Add(this);
					this._id_Fabricante = value.id_Fabricante;
				}
				else
				{
					this._id_Fabricante = default(int);
				}
				this.SendPropertyChanged("Fabricante");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado_Usuario")]
public partial class Estado_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_EstadoUsuario;
	
	private string _Descripcion;
	
	private EntitySet<Usuario> _Usuario;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_EstadoUsuarioChanging(int value);
    partial void Onid_EstadoUsuarioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
	
	public Estado_Usuario()
	{
		this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_EstadoUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_EstadoUsuario
	{
		get
		{
			return this._id_EstadoUsuario;
		}
		set
		{
			if ((this._id_EstadoUsuario != value))
			{
				this.Onid_EstadoUsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_EstadoUsuario = value;
				this.SendPropertyChanged("id_EstadoUsuario");
				this.Onid_EstadoUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Descripcion
	{
		get
		{
			return this._Descripcion;
		}
		set
		{
			if ((this._Descripcion != value))
			{
				this.OnDescripcionChanging(value);
				this.SendPropertyChanging();
				this._Descripcion = value;
				this.SendPropertyChanged("Descripcion");
				this.OnDescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Usuario_Usuario", Storage="_Usuario", ThisKey="id_EstadoUsuario", OtherKey="id_EstadoUsuario")]
	public EntitySet<Usuario> Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			this._Usuario.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Usuario(Usuario entity)
	{
		this.SendPropertyChanging();
		entity.Estado_Usuario = this;
	}
	
	private void detach_Usuario(Usuario entity)
	{
		this.SendPropertyChanging();
		entity.Estado_Usuario = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_Usuario;
	
	private string _Username;
	
	private string _Password;
	
	private string _Nombres;
	
	private string _Apellidos;
	
	private string _Imagen;
	
	private int _id_EstadoUsuario;
	
	private EntityRef<Estado_Usuario> _Estado_Usuario;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_UsuarioChanging(int value);
    partial void Onid_UsuarioChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnImagenChanging(string value);
    partial void OnImagenChanged();
    partial void Onid_EstadoUsuarioChanging(int value);
    partial void Onid_EstadoUsuarioChanged();
    #endregion
	
	public Usuario()
	{
		this._Estado_Usuario = default(EntityRef<Estado_Usuario>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_Usuario
	{
		get
		{
			return this._id_Usuario;
		}
		set
		{
			if ((this._id_Usuario != value))
			{
				this.Onid_UsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_Usuario = value;
				this.SendPropertyChanged("id_Usuario");
				this.Onid_UsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Nombres
	{
		get
		{
			return this._Nombres;
		}
		set
		{
			if ((this._Nombres != value))
			{
				this.OnNombresChanging(value);
				this.SendPropertyChanging();
				this._Nombres = value;
				this.SendPropertyChanged("Nombres");
				this.OnNombresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Apellidos
	{
		get
		{
			return this._Apellidos;
		}
		set
		{
			if ((this._Apellidos != value))
			{
				this.OnApellidosChanging(value);
				this.SendPropertyChanging();
				this._Apellidos = value;
				this.SendPropertyChanged("Apellidos");
				this.OnApellidosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string Imagen
	{
		get
		{
			return this._Imagen;
		}
		set
		{
			if ((this._Imagen != value))
			{
				this.OnImagenChanging(value);
				this.SendPropertyChanging();
				this._Imagen = value;
				this.SendPropertyChanged("Imagen");
				this.OnImagenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_EstadoUsuario", DbType="Int NOT NULL")]
	public int id_EstadoUsuario
	{
		get
		{
			return this._id_EstadoUsuario;
		}
		set
		{
			if ((this._id_EstadoUsuario != value))
			{
				if (this._Estado_Usuario.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_EstadoUsuarioChanging(value);
				this.SendPropertyChanging();
				this._id_EstadoUsuario = value;
				this.SendPropertyChanged("id_EstadoUsuario");
				this.Onid_EstadoUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Usuario_Usuario", Storage="_Estado_Usuario", ThisKey="id_EstadoUsuario", OtherKey="id_EstadoUsuario", IsForeignKey=true)]
	public Estado_Usuario Estado_Usuario
	{
		get
		{
			return this._Estado_Usuario.Entity;
		}
		set
		{
			Estado_Usuario previousValue = this._Estado_Usuario.Entity;
			if (((previousValue != value) 
						|| (this._Estado_Usuario.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Estado_Usuario.Entity = null;
					previousValue.Usuario.Remove(this);
				}
				this._Estado_Usuario.Entity = value;
				if ((value != null))
				{
					value.Usuario.Add(this);
					this._id_EstadoUsuario = value.id_EstadoUsuario;
				}
				else
				{
					this._id_EstadoUsuario = default(int);
				}
				this.SendPropertyChanged("Estado_Usuario");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class vPhonesResult
{
	
	private int _id_Smartphone;
	
	private string _Nombre;
	
	private string _Imagen;
	
	private string _Fabricante;
	
	public vPhonesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Smartphone", DbType="Int NOT NULL")]
	public int id_Smartphone
	{
		get
		{
			return this._id_Smartphone;
		}
		set
		{
			if ((this._id_Smartphone != value))
			{
				this._id_Smartphone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string Imagen
	{
		get
		{
			return this._Imagen;
		}
		set
		{
			if ((this._Imagen != value))
			{
				this._Imagen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabricante", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Fabricante
	{
		get
		{
			return this._Fabricante;
		}
		set
		{
			if ((this._Fabricante != value))
			{
				this._Fabricante = value;
			}
		}
	}
}
#pragma warning restore 1591
